import os
import sqlite3
from fpdf import FPDF
from datetime import datetime
from db import DB_PATH

REPORTS_DIR = os.path.join(os.path.dirname(os.path.abspath(DB_PATH)), "reports")



def generate_monthly_report(month: str) -> str:
    """Generate a PDF report for the given month (YYYY-MM). Returns the file path."""
    os.makedirs(REPORTS_DIR, exist_ok=True)

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    # Fetch expenses
    expenses = conn.execute(
        """
        SELECT e.date, e.description, c.name as category, e.amount, e.payment_method, e.note
        FROM expenses e
        LEFT JOIN categories c ON e.category_id = c.id
        WHERE strftime('%Y-%m', e.date) = ?
        ORDER BY e.date
        """,
        (month,)
    ).fetchall()

    # Category totals
    cat_totals = conn.execute(
        """
        SELECT c.name, COALESCE(SUM(e.amount), 0) as total
        FROM categories c
        LEFT JOIN expenses e ON e.category_id = c.id AND strftime('%Y-%m', e.date) = ?
        GROUP BY c.id
        ORDER BY total DESC
        """,
        (month,)
    ).fetchall()

    conn.close()

    total_spent = sum(row["amount"] for row in expenses)

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 12, "Personal Expense Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Month: {month}  |  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="C")
    pdf.ln(6)

    # Summary box
    pdf.set_fill_color(245, 245, 255)
    pdf.set_draw_color(180, 180, 220)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 10, f"  Total Spent: Rs. {total_spent:,.2f}    Transactions: {len(expenses)}", ln=True, fill=True)
    pdf.ln(6)

    # Category Breakdown
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, "Category Breakdown", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_fill_color(235, 235, 250)
    for i, row in enumerate(cat_totals):
        if row["total"] > 0:
            fill = i % 2 == 0
            pdf.set_fill_color(240, 240, 255) if fill else pdf.set_fill_color(255, 255, 255)
            pdf.cell(100, 7, f"  {row['name']}", fill=fill)
            pdf.cell(0, 7, f"Rs. {row['total']:,.2f}", ln=True, align="R", fill=fill)
    pdf.ln(6)

    # Expense Table
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, "Expense Details", ln=True)

    # Header row
    pdf.set_fill_color(99, 102, 241)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    col_widths = [25, 55, 35, 30, 30, 15]
    headers = ["Date", "Description", "Category", "Amount", "Method", "Note"]
    for w, h in zip(col_widths, headers):
        pdf.cell(w, 8, h, fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 9)
    for i, row in enumerate(expenses):
        pdf.set_text_color(50, 50, 50)
        if i % 2 == 0:
            pdf.set_fill_color(248, 248, 255)
        else:
            pdf.set_fill_color(255, 255, 255)
        fill = True
        pdf.cell(col_widths[0], 7, str(row["date"]), fill=fill)
        # Truncate long descriptions
        desc = str(row["description"] or "")[:30]
        pdf.cell(col_widths[1], 7, desc, fill=fill)
        pdf.cell(col_widths[2], 7, str(row["category"] or ""), fill=fill)
        pdf.cell(col_widths[3], 7, f"Rs. {row['amount']:,.2f}", fill=fill)
        pdf.cell(col_widths[4], 7, str(row["payment_method"] or ""), fill=fill)
        note = str(row["note"] or "")[:10]
        pdf.cell(col_widths[5], 7, note, fill=fill, ln=True)

    # Footer
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, "Generated by Personal Expense Tracker", ln=True, align="C")

    filename = f"report_{month}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)
    pdf.output(filepath)
    return filepath
